### ISSUE TITLE
ath10k pci probe function is not called

### ISSUE THREAD

**Issue by xueliu** [MarvellEmbeddedProcessors/openwrt-kernel#1]
Hello,

I have a clearfog A1 - Rev 2.1 board and two WLE900VX WiFi cards on it. The system in it is OpenWRT BB.

The problem is that there is no ath10k driver info out in the kernel log. And the pci probe function is never called by pci bus driver.

lspci gives no info about the WLE900VX card.

Could some one give me some suggestions ?

**Comment by rabeeh** [comment]
Hi,

Few questions -
1. What does lspci give you?
2. Which of the two mini pcie connectors are you using?
3. Have you tried both of them?
4. What is the build procedure that you have tried?

For me looks like pcie is not built at all; when running 'lspci' on ClearFog then you should see at least the two host controllers and then the peripherals connected to it.

**Comment by xueliu** [comment]
Hi,

Thank you for your feedback.
1. What does lspci give you?
root@OpenWrt:/# lspci -mm
00:02.0 "PCI bridge" "Marvell Technology Group Ltd." "88F6820 [Armada 385] ARM SoC" "" ""
00:03.0 "PCI bridge" "Marvell Technology Group Ltd." "88F6820 [Armada 385] ARM SoC" "" ""
1. Which of the two mini pcie connectors are you using?
   pcie 2 and 3 
2. Have you tried both of them?
   don't know what are "both"
3. What is the build procedure that you have tried?
   https://github.com/MarvellEmbeddedProcessors/openwrt-bb/wiki

I think the pcie driver is installed and the boot log as:
root@OpenWrt:/# dmesg | grep pci
[    1.111647] mvebu-pcie pcie-controller.3: PCIe1.0: link down
[    1.111665] mvebu-pcie pcie-controller.3: PCIe2.0: link down
[    1.111748] mvebu-pcie pcie-controller.3: PCI host bridge to bus 0000:00
[    1.111756] pci_bus 0000:00: root bus resource [io  0x1000-0xfffff]
[    1.111761] pci_bus 0000:00: root bus resource [mem 0xe0000000-0xe7ffffff]
[    1.111766] pci_bus 0000:00: root bus resource [bus 00-ff]
[    1.111770] pci_bus 0000:00: scanning bus
[    1.111784] pci 0000:00:02.0: [11ab:7846] type 01 class 0x060400
[    1.111801] pci 0000:00:02.0: calling pci_fixup_ide_bases+0x0/0x48
[    1.111890] pci 0000:00:03.0: [11ab:7846] type 01 class 0x060400
[    1.111902] pci 0000:00:03.0: calling pci_fixup_ide_bases+0x0/0x48
[    1.111985] pci_bus 0000:00: fixups for bus
[    1.111997] pci 0000:00:02.0: scanning [bus 00-00] behind bridge, pass 0
[    1.112002] pci 0000:00:02.0: bridge configuration invalid ([bus 00-00]), reconfiguring
[    1.112007] pci 0000:00:03.0: scanning [bus 00-00] behind bridge, pass 0
[    1.112011] pci 0000:00:03.0: bridge configuration invalid ([bus 00-00]), reconfiguring
[    1.112017] pci 0000:00:02.0: scanning [bus 00-00] behind bridge, pass 1
[    1.112074] pci_bus 0000:01: scanning bus
[    1.112089] pci_bus 0000:01: fixups for bus
[    1.112096] pci_bus 0000:01: bus scan returning with max=01
[    1.112101] pci_bus 0000:01: busn_res: [bus 01-ff] end is updated to 01
[    1.112107] pci 0000:00:03.0: scanning [bus 00-00] behind bridge, pass 1
[    1.112161] pci_bus 0000:02: scanning bus
[    1.112175] pci_bus 0000:02: fixups for bus
[    1.112182] pci_bus 0000:02: bus scan returning with max=02
[    1.112187] pci_bus 0000:02: busn_res: [bus 02-ff] end is updated to 02
[    1.112191] pci_bus 0000:00: bus scan returning with max=02
[    1.112200] pci 0000:00:02.0: fixup irq: got 135
[    1.112204] pci 0000:00:02.0: assigning IRQ 135
[    1.112210] pci 0000:00:03.0: fixup irq: got 135
[    1.112213] pci 0000:00:03.0: assigning IRQ 135
[    1.112224] pci 0000:00:02.0: PCI bridge to [bus 01]
[    1.112230] pci 0000:00:03.0: PCI bridge to [bus 02]
[    1.112243] pci 0000:00:02.0: enabling bus mastering
[    1.112251] pci 0000:00:03.0: enabling bus mastering
[    2.367109] ehci-pci: EHCI PCI platform driver

---

There are no info about the wifi cards from lspci. why ?

**Comment by xueliu** [comment]
The problem is solved.

The problem is that the U-Boot initializes the mSATA instead of PCIe interface.

**Comment by lperkov** [comment]
@xueliu can you please explain what did you do in U-Boot? Did you make any modifications to the code?

**Comment by xueliu** [comment]
OK. I did not make any modifications to the u-boot code.
According to the tutorial here http://wiki.solid-run.com/doku.php?id=products:a38x:software:development:u-boot,
we could switch PCIe to MSATA. The default configuration of u-boot from OpenWRT BB is using MSATA. Therefore I compile another one with PCIe.

**Comment by lperkov** [comment]
@xueliu thank you!

**Comment by vpeter4** [comment]
@xueliu: I saw on Gist that you used also firmware 19-02-2016. Can you explain the changes you did to marvel openwrt bb?

**Comment by xueliu** [comment]
Hello,

I don't quite understand the meaning of “firmware 19-02-2016”. I compile
the marvel openwrt bb and take the boot log at 19-02-2016. At that time I
did not make any changes to the source code.

Regards,

Xue Liu

2016-03-06 16:46 GMT+01:00 Peter V. notifications@github.com:

> @xueliu https://github.com/xueliu: isaw on Gist that you used also
> firmware 19-02-2016. Can you explain the changes you did to marvel openwrt
> bb?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MarvellEmbeddedProcessors/openwrt-kernel/issues/1#issuecomment-192918914
> .

##

**Comment by RaghavendraSurpur** [comment]
Hi ,
We r using WPEA352ACN(QCA9880) wifi module and now only one pcie1 is enable but pcie2 is not enable when i did lspci, So pls give me any solution..

Regards,
Raghavendra

**Comment by xueliu** [comment]
Hello Raghavendra,

Plz paste your whole boot log or you can find my boot log here
https://gist.github.com/dks-xueliu/634536579c23a555d599.

In the boot log, you can see:

BootROM - 1.73
Booting from MMC
General initialization - Version: 1.0.0
Detected Device ID 6828
High speed PHY - Version: 2.0
Init Customer board board SerDes lanes topology details:
| Lane # | Speed| Type |
------------------------------|
| 0 | 3 | SATA0 |
| 1 | 0 | SGMII1 |
| 2 | 5 | PCIe1 |
| 3 | 5 | USB3 HOST1 |
| 4 | 5 | PCIe2 |

## | 5 | 0 | SGMII2 |

Both PCIe1 and PCIe2 are enable.

Regards,

Xue Liu

2016-03-30 12:45 GMT+02:00 RaghavendraSurpur notifications@github.com:

> Hi ,
> We r using WPEA352ACN(QCA9880) wifi module and now only one pcie1 is
> enable but pcie2 is not enable when i did lspci, So pls give me any
> solution..
> 
> Regards,
> Raghavendra
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/MarvellEmbeddedProcessors/openwrt-kernel/issues/1#issuecomment-203375459

##

**Comment by sethi-preeti** [comment]
@xueliu Hey,
I am a beginner in openwrt. Can you please tell me how are you using the command 'lspci' in openwrt? It always shows command not found to me. It also says package 'pciutils' not found when I tried installing it. 
How can I make this command work?

**Comment by RaghavendraSurpur** [comment]
Try to install 'pciutils'
