### ISSUE TITLE
mvebu_net driver

### ISSUE THREAD

**Issue by ghost** [MarvellEmbeddedProcessors/openwrt-kernel#2]
Hello,

Now I am looking at the Ethernet driver of armada 38x. I have found that there are additional Ethernet driver folder call mvebu_net which is not in the mainline kernel (e.g., 4.1). Could you please give me some information about the drivers in this folder, and whether these drivers are in the other places of mainline kernel ? Thank you.

**Comment by nitroshift** [comment]
This is Marvell's in-house version of kernel that includes changes that are not submitted to vanilla kernel, nor are they upstreamable into mainline.

nitroshift
