### ISSUE TITLE
Unable to compile kernel when ath9k drivers are selected

### ISSUE THREAD

**Issue by woodrad** [MarvellEmbeddedProcessors/openwrt-kernel#3]
When I try to compile the kernel with ath9k support built-in, I get the error below. Compilation works fine when wireless support is not selected.

````
cmp /home/ec2-user/openwrt-dd/build_dir/target-aarch64_cortex-a53+neon-vfpv4_musl-1.1.16/linux-mvebu64/compat-wireless-2016-05-12/include/linux/ath9k_platform.h /home/ec2-user/openwrt-dd/build_dir/target-aarch64_cortex-a53+neon-vfpv4_musl-1.1.16/linux-mvebu64/linux-4.4.8/include/linux/ath9k_platform.h
/home/ec2-user/openwrt-dd/build_dir/target-aarch64_cortex-a53+neon-vfpv4_musl-1.1.16/linux-mvebu64/compat-wireless-2016-05-12/include/linux/ath9k_platform.h /home/ec2-user/openwrt-dd/build_dir/target-aarch64_cortex-a53+neon-vfpv4_musl-1.1.16/linux-mvebu64/linux-4.4.8/include/linux/ath9k_platform.h differ: char 1165, line 34
````

How to reproduce:
1. `git clone https://github.com/MarvellEmbeddedProcessors/openwrt-kernel.git -b openwrt_17.02_release`
2. `git clone https://github.com/MarvellEmbeddedProcessors/openwrt-dd.git -b openwrt_17.02_release`
3. `cd openwrt-dd`
4. `./scripts/feeds update -a; ./scripts/feeds install -a`
5. Copy my [`.config` file](https://gist.github.com/woodrad/9361301058087ef00e239dcdc151ff2f) to the directory
6. `make -j1 V=s`

Relevant part of my `.config` file:
````
#
# Wireless Drivers
#
CONFIG_PACKAGE_kmod-ath=y
CONFIG_PACKAGE_ATH_DFS=y
CONFIG_PACKAGE_kmod-ath9k=y
CONFIG_PACKAGE_kmod-ath9k-common=y
CONFIG_PACKAGE_kmod-cfg80211=y
CONFIG_PACKAGE_kmod-mac80211=y
CONFIG_PACKAGE_MAC80211_DEBUGFS=y
````
Here's the [gist](https://gist.github.com/woodrad/9361301058087ef00e239dcdc151ff2f) of my `.config` file and some of the [output](https://gist.github.com/woodrad/cd33993ecd0e1231c3706f1ff9a00b95) from `make -j1 V=s`.

**Comment by damirsamardzic** [comment]
I'm sorry for the late response. If this is still relevant for you, the latest commit a82c62794f5b should solve the issue.

**Comment by woodrad** [comment]
Thanks, @damirsamardzic, it compiles now!

**Comment by Insane-neal** [comment]
May I ask how did you make it compiled? I'm still facing the issue

**Comment by Insane-neal** [comment]
For those who observe the error, the solution is to make the two ath9k_platform.h the same. So just copy 
u32 bt_active_pin;
u32 bt_priority_pin;
u32 wlan_active_pin;
to one ath9k_platform.h that missing these lines.
